steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t" , "gcr.io/$PROJECT_ID/react_app", "-t" , "gcr.io/$PROJECT_ID/react_app:latest", "-f","Dockerfile.dev", "." ]
images:
  - "gcr.io/$PROJECT_ID/react_app"
  - "gcr.io/$PROJECT_ID/react_app:latest"
